### ISSUE TITLE
ds920+ failed, prompting the repair kit continuously

### ISSUE THREAD

**Issue by muyigege** [bb-qq/aqc111#101]
### Description of the problem

>ds920+ failed, prompting the repair kit continuously，After installing the suite and using the ssh repair command to repair it, the suite still says Please repair the suite. Startup failed.

### Description of your products

> - ds920+
>     - and output of ``uname -a`` command
>     - DSM version 7.1.1-42962up3
> -QNA-UC5G1T
![image](https://user-images.githubusercontent.com/39075368/218243407-d1413ccd-a96f-4aaa-8dc5-e2e20fd5f571.png)

**Comment by bb-qq** [comment]
Could you post the content of `/var/packages/r8152/var/log/start-stop-status.log`.

**Comment by bb-qq** [comment]
Since there has been no response for a long time, this issue is closed. Please feel free to re-open it if you have any questions.
