### ISSUE TITLE
Woudl like to try with DS413 

### ISSUE THREAD

**Issue by LauraMSchreiber** [bb-qq/aqc111#106]
### Description of the problem

I didn't find a driver/spk for the Freescale P1022 / OOriq architectore of the DS413 NAS. Is there an alternative I could use?

### Description of your products

> Synology product name: DS413
>     - and output of ``uname -a`` command:
Linux SynoWue 2.6.32.12 #25556 SMP Thu Jul 1 14:30:01 CST 2021 ppc GNU/Linux synology_qoriq_413
>     - DSM version: 6.2.4-25556 Update 6 
> - the product name of the ethernet dongle:
QNAP QNA-UC5G1T USB 3.0 to 5Gbe Adapter

### Description of your environment
- PC:  AMD Threadripper 3270X / TRX40 10G Pro
- Hub: Zyxel XGS1250
- cable category : Cat.7

### Output of ``dmesg`` command

````
(paste output here)
````

### Output of ``lsusb`` command
|__usb1          1d6b:0002:0206 09  2.00  480MBit/s   0mA 1IF  (Linux 2.6.32.12 ehci_hcd Freescale On-Chip EHCI Host Controller fsl-ehci.0) hub
|__usb2          1d6b:0003:0206 09  3.00 5000MBit/s   0mA 1IF  (xhci_hcd 0002:05:00.0) hub
````
(paste output here)
````

Thanks for any hint I could workk with!

**Comment by bb-qq** [comment]
This platform `synology_qoriq_413` does not seem to be supported by Synology Toolkit and I don't know how to build a driver for it. Sorry.
https://archive.synology.com/download/ToolChain/toolkit/6.2
