### ISSUE TITLE
Sabrent NT-SS5G last driver aqc111-apollolake-1.3.3.0-10 outdated on DS418play upgraded to DSM7.2

### ISSUE THREAD

**Issue by YVES59** [bb-qq/aqc111#111]
Although this last driver version was fully functional on DS418play with DSM 7.1.1, unfortunately failed to (re)install properly  after the DSM 7.2 upgrade.
Help from the skilled Synology driver developers is requested, many thanks !!!

Best Regards

**Comment by bb-qq** [comment]
Updating DSM may require a complete reinstallation of the package.

This Issue may be useful to you.
https://github.com/bb-qq/r8152/issues/309

**Comment by bb-qq** [comment]
Since there has been no response for a long time, this issue is closed. Please feel free to re-open it if you have any questions.
