### ISSUE TITLE
Getting 2 different parts of issues at the install

### ISSUE THREAD

**Issue by rifaterdemsahin** [bb-qq/aqc111#112]
**First part i the error I get after first install**

<img width="851" alt="image" src="https://github.com/bb-qq/aqc111/assets/5270036/b4f9d445-5593-4141-8eda-346beca87621">

In second install
<img width="646" alt="image" src="https://github.com/bb-qq/aqc111/assets/5270036/45541690-5aea-46f5-8217-75485acd785c">
<img width="493" alt="image" src="https://github.com/bb-qq/aqc111/assets/5270036/574acdcd-ad34-463d-8e4a-0209b56050ea">
for couple of minutes
<img width="761" alt="image" src="https://github.com/bb-qq/aqc111/assets/5270036/48eb01ad-5dff-4751-9894-ed117498b143">
and restarted

I installed the driver to 918+ ( aqc111-apollolake-1.3.3.0-11_7.1.spk )

I did run the command over SSH
sudo install -m 4755 -o root -D /var/packages/aqc111/target/aqc111/spk_su /opt/sbin/spk_su

After restart
<img width="792" alt="image" src="https://github.com/bb-qq/aqc111/assets/5270036/848c7c3c-6cc5-45b1-9292-fd00c2f02a37">

Is this all I need to do ?

**Second part is**
I am getting a 5G card to Synology take the data from the 10G connected Uni switch
<img width="854" alt="image" src="https://github.com/bb-qq/aqc111/assets/5270036/32fd4ed6-499c-42d0-89c9-93a2771fe670">

What kind of speed should I expect?

**Comment by bb-qq** [comment]
> Is this all I need to do ?

Yes.

> What kind of speed should I expect?

I have a concern regarding the choice on the transceiver side.

Many transceivers support only 1Gbps/10Gbps and often do not support the later standards 2.5Gbps/5Gbps. So please refer to the product datasheet and choose one that explicitly states that it supports IEEE 802.3bz.

I do not know if the product you mention is supported or not.

**Comment by bb-qq** [comment]
Since there has been no response for a long time, this issue is closed. Please feel free to re-open it if you have any questions.
