### ISSUE TITLE
QNAP TS-233

### ISSUE THREAD

**Issue by pihokkerr** [bb-qq/aqc111#125]
### Unsupported adapter 

Would it be possible to implement the project for unsupported QNAP NAS as well? When the TS-233 NAS was released, the QNA-UC5G1T product was still among the compatible devices, but a few months later it was removed, and it hasn't worked since.

### Description of your products

> QNAP TS-233
> CPU: 64-bit ARM Cortex-A55
> QTS 5.1.2
> QNA-UC5G1T

**Comment by bb-qq** [comment]
I do not have the skills to develop a driver for QNAP. And if they dare to stop supporting the device, I guess there is a technical reason.

**Comment by Dmedia3412** [comment]
Add in autorun.sh

modprobe aqc111
ethtool --set-priv-flags eth2 "Thermal throttling" off
ethtool --set-priv-flags eth2 "Low Power 5G" on

**Comment by bb-qq** [comment]
I am sorry, but there is nothing more I can do for you, so I am closing this issue.
