### ISSUE TITLE
New USB Adaptor not seen in network interface

### ISSUE THREAD

**Issue by mlc130104** [bb-qq/aqc111#27]
Issue: USB device detected by DSM but not showing up in network interface:

![2020-09-25_191222](https://user-images.githubusercontent.com/7189975/94260645-21ac3300-ff63-11ea-9afb-e498164e5e3d.png)

![2020-09-25_191419](https://user-images.githubusercontent.com/7189975/94260794-5ddf9380-ff63-11ea-8d4b-ead9bebcffb8.png)

Vendor and Device ID:

![2020-09-25 (1)](https://user-images.githubusercontent.com/7189975/94260694-3688c680-ff63-11ea-96cf-41a0b91c64f5.png)

**Comment by bb-qq** [comment]
Please paste outputs of `dmesg` and `ifconfig -a`.

**Comment by mlc130104** [comment]
Hello,

The problem is fixed after a reboot, thanks!

**Comment by bb-qq** [comment]
That's good to hear. Closing.
