### ISSUE TITLE
Support for DS1515+ with an Intel Atom C2538?

### ISSUE THREAD

**Issue by TaylorTMusic** [bb-qq/aqc111#3]
Is there a way to compile a version that works with the DS1515+? I wanted to check first before I installed the aqc111-denverton-1.3.3.0-1.spk driver, but might just test and see as that's the oldest driver package.

**Comment by kachunkachunk** [comment]
@TaylorTMusic - how'd it fare? I have a 1515+ myself.

**Comment by Ryrynz** [comment]
> I wanted to check first before I installed the aqc111-denverton-1.3.3.0-1.spk driver, but might just test and see as that's the oldest driver package.

Did it work?
