### ISSUE TITLE
Driver issue with UGREEN 5GBE Adapter

### ISSUE THREAD

**Issue by ilovemissjni** [bb-qq/aqc111#39]
I just brought the ugreen 5gbe adapter from china. When I plug into my 920+, I can't see LAN 3 with driver version 1.3.3.0-2.

I had asked google.com, he said this adapter use the same chip with UC5G1T.

Is it possible to support this adapter?

Aquantia 5G USB Ethernet Adapter - Aquantia VID:2eca PID:c101 REV:1.01

THX!!!

**Comment by bb-qq** [comment]
Could you paste the result of `lsusb`?

**Comment by ilovemissjni** [comment]
> Could you paste the result of `lsusb`?

`/$ lsusb
|__usb1          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.59+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__1-4         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 7F000B5B2A13F201)
|__usb2          1d6b:0003:0404 09  3.00 5000MBit/s 0mA 1IF  (Linux 4.4.59+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__2-1         2eca:c101:0101 00  3.20 5000MBit/s 896mA 2IFs (Aquantia Aquantia 5G USB Ethernet Adapter 00000072)
ilovemissjni@ilovemissjni:/$
`

**Comment by bb-qq** [comment]
I guess that driver is working correctly, but NIC is not configured properly due to the DHCP-related bug in my driver package.
Using  1.3.3.0-3 will resolve the issue.

**Comment by bb-qq** [comment]
I close the issue due to no response. Please feel free to re-open the issue.
