### ISSUE TITLE
Can't install on 918+ on DSM7

### ISSUE THREAD

**Issue by leshokunin** [bb-qq/aqc111#40]
I'm trying the manual install on my Synology 918+. I picked the apollolake version (in fact, I tried both releases). When I try to install it, it says can't install, wrong format.

I'm on DSM 7.
Any idea?

**Comment by tuananh** [comment]
ah i was about to ask the same question. subscribing to this now

**Comment by ihvar** [comment]
It also doesn't work on 418play with DSM 7

**Comment by bb-qq** [comment]
Duplicate of #26
