### ISSUE TITLE
readme mixed up

### ISSUE THREAD

**Issue by Benniphx** [bb-qq/aqc111#49]
in the aqc111 readme is the link to the r8152/releases instead of the aqc111/releases.

this part:
"
You can download drivers including other platforms from the Release page and determine a proper driver for your model from this page, but you might encounter some issues with unconfirmed platforms.
"

I was checking what I did wrong until I noticed i downloaded the wrong driver 

thx

**Comment by bb-qq** [comment]
Thanks for pointing out the incorrect link. I fixed it.
