### ISSUE TITLE
need help with compiling usbnet.c

### ISSUE THREAD

**Issue by iwanovich** [bb-qq/aqc111#5]
Using the [Synology Packaging Toolkit](https://github.com/SynologyOpenSource/pkgscripts-ng) and compiling for braswell (linux kernel 3.10.x) I'm getting compile errors for usbnet.c because `struct usbnet` in linux/usb/usbnet.h does not have `rx_qlen`.
usbnet.c in this repoistory comes from a newer kernel, according to your commit message. How did you compile usbnet.ko for the braswell SPK?

**Comment by bb-qq** [comment]
I forgot to push the change for that. I pushed it.

**Comment by bb-qq** [comment]
Please feel free to re-open if still something wrong.
