### ISSUE TITLE
DS 416 (alpine4k) support

### ISSUE THREAD

**Issue by momo198554** [bb-qq/aqc111#52]
Hello, 
is it possible to add support for DS 416 with alpine4k?
I am using QNAP QNA-UC5G1T (so Aquantia AQC111U) 

DS416, DSM 7.0.1.-42218, 
manually uploaded "aqc111-alpine-1.3.3.0-4.spk" in package center, pop-up message "the package is not supported on the platform of Diskstation or is incompattible with the current DSM version. 

[https://github.com/bb-qq/r8152/issues/126](url)
is the same problem like mine but with the r8152 adapters, here you seem to solve the issue. 
(See the last comments in the linked issue)

Thank you for your work!

**Comment by bb-qq** [comment]
Try this package. https://github.com/bb-qq/aqc111/releases/download/1.3.3.0-4/aqc111-alpine4k-1.3.3.0-4.spk
I would appreciate it if you report whether it works and its stability.
