### ISSUE TITLE
Big sur driver?

### ISSUE THREAD

**Issue by jameslashmar** [bb-qq/aqc111#53]
Hi, apologies for creating an issue, however it is the only way that I can message you.

The driver for the same 5gbit adaptor no longer works on macOS due to Big Sur changing how extensions work. 

Do you have any plans to release a mac compatible driver for the series of adaptor? I think there would be a huge demand for it!

Thanks!

**Comment by bb-qq** [comment]
Sorry, I don't have any computers supporting MacOS, so I can't develop a driver for it.
