### ISSUE TITLE
1.3.3.0-5 DSM-7.0 Release note typo

### ISSUE THREAD

**Issue by PureWhiteWu** [bb-qq/aqc111#60]
The release note for 1.3.3.0-5 DSM-7.0 now indicates we need to do this:
```
sudo install -m 4755 -o root -D /var/packages/r8152/target/r8152/spk_su /opt/sbin/spk_su
```

Maybe this is a typo? The package name should be aqc111, so the command we need to execute is:
```
sudo install -m 4755 -o root -D /var/packages/aqc111/target/aqc111/spk_su /opt/sbin/spk_su
```

**Comment by bb-qq** [comment]
Oops! I fixed that. Thank you.
