### ISSUE TITLE
1.3.3.0-5 DSM-7.0 ssh command typo in note

### ISSUE THREAD

**Issue by david-born** [bb-qq/aqc111#62]
sudo install -m 4755 -o root -D /var/packages/**_acc111_**/target/**_acc111_**/spk_su /opt/sbin/spk_su

sudo install -m 4755 -o root -D /var/packages/**_aqc111_**/target/**_aqc111_**/spk_su /opt/sbin/spk_su

Thank you!

**Comment by bb-qq** [comment]
Thank you. I fixed.
