### ISSUE TITLE
Two installations on DSM, both now can't get above 1gb

### ISSUE THREAD

**Issue by wdwms** [bb-qq/aqc111#65]
### Description of the problem

Got a DS418+ Play and a DS920+; both now despite trying everything for some reason will not go above 1G. I've not done anything but upgrade DSM when new versions come out. Trying an MTU of 9000 didn't help the issue.

Both are running DSM 7.0.1-42218 Update 3
Both have the latest version of the driver, I've tried turning off thermal throttling, nothing.
They are both connected directly to a 10G switch and proper link lights show both linked at 5G
I'm testing by running iperf between the two boxes.

Linux Peabody 4.4.180+ #42218 SMP Mon Oct 18 19:16:55 CST 2021 x86_64 GNU/Linux synology_geminilake_920+
Linux LBVHS 4.4.180+ #42218 SMP Mon Oct 18 19:17:56 CST 2021 x86_64 GNU/Linux synology_apollolake_418play

Both have the QNA-UC5G1T installed, plugged into the front. Cat 7 cable

Honestly, at this point I'm ready to throw in the towel, its clear I can't get any better performance from these devices.. what am I to do?

### Output of ``lsusb`` command

````
|__usb1          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.180+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__1-2         0764:0601:0200 00  2.00   12MBit/s 2mA 1IF  (CPS OR700LCDRM1Ua GA5LP2000250)
  |__1-4         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 7F00119D9113F229)
|__usb2          1d6b:0003:0404 09  3.00 5000MBit/s 0mA 1IF  (Linux 4.4.180+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__2-1         1c04:0015:0101 00  3.20 5000MBit/s 896mA 1IF  (QNAP QNAP QNA-UC5G1T USB to 5GbE Adapter 16I00486)

|__usb1          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.180+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__1-4         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 7F008BCA3A6DAE66)
|__usb2          1d6b:0003:0404 09  3.00 5000MBit/s 0mA 1IF  (Linux 4.4.180+ xhci-hcd xHCI Host Controller 0000:00:15.0) hub
  |__2-1         1c04:0015:0101 00  3.20 5000MBit/s 896mA 1IF  (QNAP QNAP QNA-UC5G1T USB to 5GbE Adapter 13I14879)
````

### Output of ``ifconfig -a`` command

````
tmccartn@Peabody:/$ ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:11:32:EC:E8:57
          inet addr:169.254.71.26  Bcast:169.254.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:89 base 0xc000

eth1      Link encap:Ethernet  HWaddr 00:11:32:EC:E8:58
          inet addr:192.168.2.25  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::211:32ff:feec:e858/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13094 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10461 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3937290 (3.7 MiB)  TX bytes:6444159 (6.1 MiB)
          Interrupt:88 base 0xe000

eth2      Link encap:Ethernet  HWaddr 24:5E:BE:65:53:09
          inet addr:192.168.2.20  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::265e:beff:fe65:5309/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1639964 errors:1 dropped:0 overruns:0 frame:0
          TX packets:203216 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2450773209 (2.2 GiB)  TX bytes:16587280 (15.8 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:5070 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5070 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:958138 (935.6 KiB)  TX bytes:958138 (935.6 KiB)

sit0      Link encap:IPv6-in-IPv4
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)



admin@LBVHS:/$ ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:11:32:A0:72:41
          inet addr:192.168.2.35  Bcast:192.168.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:456252 errors:0 dropped:0 overruns:0 frame:0
          TX packets:383745 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:40023975 (38.1 MiB)  TX bytes:4753957145 (4.4 GiB)
          Interrupt:115 base 0x4000

eth1      Link encap:Ethernet  HWaddr 00:11:32:A0:72:42
          inet addr:169.254.30.115  Bcast:169.254.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:116

eth2      Link encap:Ethernet  HWaddr 24:5E:BE:5B:F9:64
          inet addr:192.168.2.30  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::265e:beff:fe5b:f964/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2562 errors:1 dropped:0 overruns:0 frame:0
          TX packets:939 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:287114 (280.3 KiB)  TX bytes:125656 (122.7 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2207 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2207 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:282063 (275.4 KiB)  TX bytes:282063 (275.4 KiB)

sit0      Link encap:IPv6-in-IPv4
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

````

**Comment by wdwms** [comment]
Ok did some more digging. it is not the devices as I took both dongles off and hooked them up to a PC and ran test on both between the PC and another PC and got 3.5Gbps.  I then tested each going from a PC to the synology and was capped at 1Gb both ways.

I'm suspect synology has done something in the latest DSM to cap the network bandwidth at 1Gb, what can we look at to test this?

**Comment by bb-qq** [comment]
Could you try to assign the different subnet for each devices? Traffic may not be routed to the proper interface.

**Comment by bb-qq** [comment]
I have come up with an easier way. Could you try to unplug all the cables connected to the built-in Ethernet and see if there is any change in throughput?

**Comment by kallisti5** [comment]
I'm having the same issue on my older DS412+ (DSM 6.2) [details](https://github.com/bb-qq/aqc111/issues/63#issuecomment-1115367956)

Unplugged all onboard network.   Same issue remains plugged solely into the Sabrent 5G Network Adapter.

**Comment by wdwms** [comment]
@bb-qq are we going to get an update or anything else? I'm ready to stop using this, been a headache to use.. possibly I should just try a 2.5gb adapter?

**Comment by bb-qq** [comment]
Regarding DS920+ , there are many reports of working without issues, so this performance issue could be resolved.

Since the symptoms are similar for the DS418+Play, I initially suspected a network configuration or compatibility issue with the switch. However, if disconnecting other cables and connecting directly to the PC(cross-link) does not improve the situation, this seems unlikely.

If the network connection itself is not stable, the following command may improve the situation, but I am not sure if it will help with poor performance.

```
sudo /sbin/sysctl -w vm.min_free_kbytes=1024000
```

I don't know if the symptoms improve when moving to realtek adapters. If it is just a compatibility issue with your hardware, it may improve.

**Comment by wdwms** [comment]
@bb-qq I can tell you i've got 2 issues.

1. Continued use of the device causes it to stop functioning, the only way to fix it is to restart the service or device. I had a 73gb file to download yesterday, I had to restart 3 times, after about 20gb it ceased to operate.
2. I can't get more that 1gb connection, no matter what I do.

#1 has been like that since the start, #2 only started with DMS 7.1

**Comment by bb-qq** [comment]
I have integrated some settings discussed in this forum into the latest release in order to help improve stability.
With this release you might see some improvement with respect to DS920+.
https://github.com/bb-qq/aqc111/releases/tag/1.3.3.0-7

**Comment by wdwms** [comment]
Thank you, i've installed it both on my 418Play and DS920+... initial iperf tests show it above 1Gb on both, will report back to see if stability and speed hold. thanks!

**Comment by bb-qq** [comment]
Since there has been no response for a long time, this issue is closed. Please feel free to re-open it if you have any questions.
