### ISSUE TITLE
Driver 1.3.3.0-5 DSM-7.0

### ISSUE THREAD

**Issue by joseefmpcc71** [bb-qq/aqc111#72]
### Description of the problem

> When I put the command: sudo install -m 4755 -o root -D /var/packages/aqc111/target/aqc111/spk_su /opt/sbin/spk_su
by SSH in my nas DS720+, It said invalid option - - '/' Why? .

### Description of your products

> - Synology NAS DS720+
>     - DSM version 7.0.1-42218 Update 3
> - QNA-UC5G1T

**Comment by bb-qq** [comment]
What happens if I explicitly specify /bin?

`sudo /bin/install -m 4755 -o root -D /var/packages/aqc111/target/aqc111/spk_su /opt/sbin/spk_su`

**Comment by joseefmpcc71** [comment]
Hello,
First thanks you for your answer,
I could install the code but I have this erro yet.
Do you know what is the solution?
Regards

________________________________
De: bb-qq ***@***.***>
Enviado: sábado, 28 de mayo de 2022 6:03
Para: bb-qq/aqc111 ***@***.***>
CC: joseefmpcc71 ***@***.***>; Author ***@***.***>
Asunto: Re: [bb-qq/aqc111] Driver 1.3.3.0-5 DSM-7.0 (Issue #72)


What happens if I explicitly specify /bin?

sudo /bin/install -m 4755 -o root -D /var/packages/aqc111/target/aqc111/spk_su /opt/sbin/spk_su

**Comment by jsiryana** [comment]
also having the same issue

**Comment by bb-qq** [comment]
Could you paste the outputs of these commands?

* `/bin/install --version`
* `/bin/install --help`

**Comment by bb-qq** [comment]
I am closing this issue as I have not heard back in a long time. Feel free to re-open it if you have any questions.
