### ISSUE TITLE
Only 1000 Mbit with StarTech & Qnap USB Adapter - DS910+ (apollolake)

### ISSUE THREAD

**Issue by xthilox** [bb-qq/aqc111#81]
### Description of the problem

> We tried both Adapter, Startech and Qnap, with both Adapters its not possible to reach 5 Gbit

### Description of your products

> - DS 920+
>     DSM Version DSM 7.1-42661
> - StarTech.com US5GA30 & Qnap QNA-UC5G1T USB 3.0

### Description of your environment

> - connect directly to a PC or using a hub
>     - Mac Studio with 10 Gbit
>     - Hub: Aruba - 10 Gbit
> - cable category (Cat.6 or Cat.7)

### Output of ``dmesg`` command

````
(paste output here)
````

### Output of ``lsusb`` command

````
(paste output here)
````

### Output of ``ifconfig -a`` command

````
(paste output here)
````

**Comment by xthilox** [comment]
no idea or update available? we still have the Problem that its just working at 1000 mbit

**Comment by bb-qq** [comment]
Did you check the [Troubleshooting](https://github.com/bb-qq/r8152/wiki/Troubleshooting) page?

**Comment by xthilox** [comment]
Yes we checked the Troubleshooting page .. we tried fe also a Y-Cable .. but its still just 1000 Mbit .. so if you have any thoughts or idea .. VERY Welcomed. Thank you!

**Comment by xthilox** [comment]
<img width="1117" alt="Bildschirmfoto 2022-09-28 um 09 41 59" src="https://user-images.githubusercontent.com/112406636/192720092-838c5c4e-28bd-477f-ac92-4f922297bacf.png">

Here an additional screenshot

**Comment by bb-qq** [comment]
In my environment, the link is up at 1000mbps on infrequent occasions, but in this case, reconnecting the cable resolves the issue.

If the issue always seems to occur, changing the cable may improve the situation. I recommend using CAT6A cable.

**Comment by KipiKland** [comment]
Or check of there is routing involved and, in such case, router being also managing such network speed

**Comment by bb-qq** [comment]
This is probably an auto-negotiation issue. You may want to use this procedure to fix the speed on the Synology side or fix the speed of the opposing device.
https://github.com/bb-qq/r8152/wiki/Troubleshooting#disable-auto-negotiation
You also need to check if the switch supports multi-gig.

By the way, since there has been no response for a long time, this issue is closed. Please feel free to re-open it if you have any questions.
