### ISSUE TITLE
DS220+ SPK can't work

### ISSUE THREAD

**Issue by bg2vcj** [bb-qq/aqc111#87]
DS220+ 
SPK can't work
DM:7.1.1-42962
QNA-UC5G1T
use aqc111-geminilake-1.3.3.0-9.spk
After installation, does not work.
“driver for aquantia AQC111U based usb ethernet adapters [dsm7 note] the installation will fail the first time”
please help me

thanks

**Comment by bg2vcj** [comment]
remark：
plug out QNA-UC5G1T  USB
aqc111 SPK  can runing
(Can be stopped and run)

plug in QNA-UC5G1T USB
aqc111 SPK  can't run
Startup failed
Needs to be fixed

**Comment by bg2vcj** [comment]
[aqc111-geminilake-1.3.3.0-10.spk](https://github.com/bb-qq/aqc111/releases/download/1.3.3.0-10/aqc111-geminilake-1.3.3.0-10.spk)  working
thanks

**Comment by bg2vcj** [comment]
new question:
NAS write rate: 250-260M/s
Reading rate: 150-160M/s
please fix

**Comment by bb-qq** [comment]
I close this issue since the issue was resolved.
I would appreciate it if you report the test result in this thread.
https://github.com/bb-qq/aqc111/issues/79
