### ISSUE TITLE
DS918+ 7.1.1 can't install the driver

### ISSUE THREAD

**Issue by hxy770128** [bb-qq/aqc111#94]
When my DS918+ was 6.2.3 the  Marvell AQtion 10Gbit Network Adapter was working. Recently I updated to 7.1.1, no NIC any more. I am looking for the driver anywhere. Your driver looks very close. But when I install the spk file, it shows not installed successful.
I am running the command you provided but still not working.
How can I fix this issue?
Thanks.
Sean

**Comment by bb-qq** [comment]
> Marvell AQtion 10Gbit Network Adapter

Can you give us specific product names and distributors?

**Comment by bb-qq** [comment]
Since there has been no response for a long time, this issue is closed. Please feel free to re-open it if you have any questions.
