### ISSUE TITLE
DS218Play - Driver crash after installation

### ISSUE THREAD

**Issue by War3333** [bb-qq/aqc111#97]
### Description of the problem

After installation NAS become unreachable. After a manual reboot the driver is installed in packet manager but with an error that says to check "Storage Manager"
I also tried to install without executing, it install perfectly but if I try to execute the nas crashes as before.
I know that on my platform the driver is unstable just wanted to try.,
any suggestion?

### Description of your products

NAS: Synology DS218Play
DSM: 7.1.1-42962 Update 3
Adapter: QNA-UC5G1T
Driver: 1.3.3.0-10 DSM-7.x (reuploaded)
RAM: 1GB
Other USB Port used for: External HD

```
 lsusb -ci
|__usb2          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.180+ xhci-hcd xHCI Host Controller xhci-hcd.2.auto) hub
|__usb3          1d6b:0003:0404 09  3.00 5000MBit/s 0mA 1IF  (Linux 4.4.180+ xhci-hcd xHCI Host Controller xhci-hcd.2.auto) hub
  |__3-1         1c04:0015:0101 00  3.20 5000MBit/s 896mA 2IFs (QNAP▒ Pacific▒ 06I14062)
  3-1:2.0         (IF) 02:06:00 1EP  ()
  3-1:2.1         (IF) 0a:00:00 0EPs ()
|__usb4          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.180+ xhci-hcd xHCI Host Controller xhci-hcd.5.auto) hub
|__usb5          1d6b:0003:0404 09  3.00 5000MBit/s 0mA 1IF  (Linux 4.4.180+ xhci-hcd xHCI Host Controller xhci-hcd.5.auto) hub
  |__5-1         1058:1048:1022 00  3.00 5000MBit/s 896mA 1IF  (Western Digital Elements 1048 575842314135335636323631)
  5-1:1.0         (IF) 08:06:50 2EPs () usb-storage host2 (sdq)
```

uname -a
Linux Varie 4.4.180+ #42962 SMP Tue Oct 18 15:07:11 CST 2022 aarch64 GNU/Linux synology_rtd1296_ds218play

**Comment by bb-qq** [comment]
Many problems have been reported regarding the rtd1296 platform. Unfortunately, we have not found a way to remedy the symptoms at this time. Please see this [Issue](https://github.com/bb-qq/r8152/issues/275) for more information.

I merge this issue to it for consolidating information.
